name: Deploy to CloudPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy latest changes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CP_HOST }}
          username: ${{ secrets.CP_USER }}
          key: ${{ secrets.CP_SSH_KEY }}
          script: |
            cd ${{ secrets.CP_PATH }}
            git fetch origin main
            git reset --hard origin/main